### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [imding/imding.github.io#15]
Hello, <br/> <br/>I'm the creator of the TopDown Engine, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by imding** [comment]
Hi Renaud,

I'm terribly sorry about that, I had purchased it for one of my students as
he did not have the means to transact online. I have removed all related
files as requested.

Hope you're staying safe & keep up the awesome work you're doing!

Regards
Ding
